[package]
name = "hack_template"
version = "0.1.0"


[dependencies]
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git" }
pragma_lib = { git = "https://github.com/astraly-labs/pragma-lib" }
starknet = ">=2.5.1"


[[target.starknet-contract]]

# Enable Sierra codegen.
sierra = true

# Enable CASM codegen.
casm = true

# Emit Python-powered hints in order to run compiled CASM class with legacy Cairo VM.
casm-add-pythonic-hints = true

allowed-libfuncs-list.name = "audited"
